version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2021-10-09T02-53-05Z
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin
    ports:
      - '9000:9000'
    volumes:
      - minio:/data
volumes:
  db:
    driver: local